filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.json
  json.keys_under_root: true
  json.add_error_key: true
  


output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "general-index-%{+yyyy.MM.dd}"

setup.template:
  name: "general-index"
  pattern: "general-index-*"

