filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.json

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
  - add_fields:
      target: ""
      fields:
        log_type: "my_app"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "general-index-%{+yyyy.MM.dd}"

setup.template:
  name: "general-index"
  pattern: "general-index-*"

